### ISSUE TITLE
Add more flexible intervals

### ISSUE THREAD

**Issue by mneumark** [linuxserver/davos#11]
This tool is exactly what I wanted except I need it to run every minute. Seems like it would not be too complicated to allow the user to override it using a text box.

Thanks!

**Comment by JAGFin1** [comment]
This should be easy enough. I'll add in a text box that overrides the default options.

**Comment by JAGFin1** [comment]
While not a complicated thing to add, instead of adding a text box, I've simply added some more interval times to the dropdown; primarily for you, I've added "Every minute" and "Every 5 minutes". I hope this is OK. As release 2.1.0 has a fair amount of enhancements in it, I wanted to speed up the process so everyone can use it sooner.
